name: Ejecutar script y subir Excel

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Funciona correctamente"
