name: Ejecutar script y subir Excel (TEST cada 5 min)

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos (UTC)
  workflow_dispatch:       # Permite ejecución manual desde la interfaz

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de facturas
        run: python facturas.py

      - name: Subir Excel generado al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add facturas_alegra.xlsx
          git diff --cached --quiet || git commit -m "Actualización automática del Excel"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
