      - name: Subir Excel generado al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add facturas_alegra.xlsx
          git commit -m "Actualización automática del archivo Excel"
          git push
